import { getAppUrl } from '@/lib/supabase/config'
import { formatCurrency } from '@/lib/utils/format-currency'

type DocusealInput = {
  contract: {
    id: string
    ref_code: string
    title: string
    description: string | null
    currency: string
    total_value: number
    terms: string | null
    created_at: string
    initiator_name: string
    counterparty_name: string
    counterparty_email: string
    milestones: Array<{
      title: string
      description: string | null
      amount: number
      deadline: string | null
    }>
  }
}

type DocusealSubmission = {
  id?: number
  submission_url?: string | null
  audit_log_url?: string | null
  combined_document_url?: string | null
}

function isConfigured(value?: string) {
  return Boolean(value && !value.startsWith('your_'))
}

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

function renderContractHtml(input: DocusealInput['contract']) {
  const milestoneItems = input.milestones
    .map((milestone, index) => {
      const deadline = milestone.deadline
        ? `<div style="color:#64748b;font-size:12px;margin-top:4px;">Due ${escapeHtml(
            milestone.deadline
          )}</div>`
        : ''

      const description = milestone.description
        ? `<p style="margin:6px 0 0;color:#334155;font-size:13px;line-height:1.6;">${escapeHtml(
            milestone.description
          )}</p>`
        : ''

      return `
        <div style="padding:14px 0;border-top:1px solid #e2e8f0;">
          <div style="display:flex;justify-content:space-between;gap:16px;">
            <div>
              <div style="font-weight:600;color:#0f172a;font-size:14px;">${
                index + 1
              }. ${escapeHtml(milestone.title)}</div>
              ${deadline}
              ${description}
            </div>
            <div style="font-weight:600;color:#0f172a;font-size:14px;white-space:nowrap;">
              ${escapeHtml(formatCurrency(milestone.amount, input.currency))}
            </div>
          </div>
        </div>
      `
    })
    .join('')

  return `
    <div style="font-family:Arial,sans-serif;padding:40px;color:#0f172a;">
      <div style="margin-bottom:24px;">
        <div style="font-size:12px;letter-spacing:0.08em;color:#64748b;margin-bottom:8px;">${escapeHtml(
          input.ref_code
        )}</div>
        <h1 style="margin:0 0 8px;font-size:28px;line-height:1.2;">${escapeHtml(
          input.title
        )}</h1>
        <p style="margin:0;color:#475569;font-size:14px;">Generated by Contrakts on ${escapeHtml(
          input.created_at
        )}</p>
      </div>
      ${
        input.description
          ? `<p style="font-size:14px;line-height:1.7;color:#334155;margin:0 0 20px;">${escapeHtml(
              input.description
            )}</p>`
          : ''
      }
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px;">
        <div style="padding:16px;border:1px solid #e2e8f0;border-radius:12px;">
          <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#64748b;margin-bottom:6px;">Initiator</div>
          <div style="font-size:15px;font-weight:600;">${escapeHtml(
            input.initiator_name
          )}</div>
        </div>
        <div style="padding:16px;border:1px solid #e2e8f0;border-radius:12px;">
          <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#64748b;margin-bottom:6px;">Counterparty</div>
          <div style="font-size:15px;font-weight:600;">${escapeHtml(
            input.counterparty_name
          )}</div>
          <div style="font-size:13px;color:#64748b;margin-top:4px;">${escapeHtml(
            input.counterparty_email
          )}</div>
        </div>
      </div>
      <div style="padding:16px;border:1px solid #e2e8f0;border-radius:12px;margin-bottom:24px;">
        <div style="font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#64748b;margin-bottom:8px;">Contract value</div>
        <div style="font-size:22px;font-weight:700;">${escapeHtml(
          formatCurrency(input.total_value, input.currency)
        )}</div>
      </div>
      <div style="padding:20px;border:1px solid #e2e8f0;border-radius:16px;margin-bottom:24px;">
        <div style="font-size:12px;text-transform:uppercase;letter-spacing:0.08em;color:#64748b;margin-bottom:8px;">Milestones</div>
        ${milestoneItems || '<p style="margin:0;color:#64748b;">No milestones recorded.</p>'}
      </div>
      <div style="padding:20px;border:1px solid #e2e8f0;border-radius:16px;">
        <div style="font-size:12px;text-transform:uppercase;letter-spacing:0.08em;color:#64748b;margin-bottom:8px;">Terms</div>
        <div style="font-size:13px;line-height:1.8;white-space:pre-wrap;color:#334155;">${escapeHtml(
          input.terms ?? 'No terms recorded.'
        )}</div>
      </div>
    </div>
  `
}

export async function generateSignedContractPdf(input: DocusealInput) {
  const apiUrl = process.env.DOCUSEAL_API_URL
  const apiToken = process.env.DOCUSEAL_API_TOKEN

  if (!isConfigured(apiUrl) || !isConfigured(apiToken)) {
    return null
  }

  try {
    const response = await fetch(`${apiUrl}/submissions/html`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Auth-Token': apiToken!,
      },
      body: JSON.stringify({
        name: `${input.contract.ref_code} ${input.contract.title}`,
        send_email: false,
        order: 'random',
        completed_redirect_url: `${getAppUrl()}/contracts/${input.contract.id}`,
        html: renderContractHtml(input.contract),
        submitters: [
          {
            name: input.contract.counterparty_name,
            email: input.contract.counterparty_email,
            role: 'Counterparty',
            completed: true,
            external_id: input.contract.id,
          },
        ],
      }),
    })

    if (!response.ok) {
      return null
    }

    return (await response.json()) as DocusealSubmission
  } catch {
    return null
  }
}
